version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: discount
    build:
      context: ./discount
      dockerfile: Dockerfile
    hostname: discount
    restart: always
    logging: *default-logging