version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: basic-dmn
    build:
      context: ./basic-dmn
      dockerfile: Dockerfile
    hostname: basic-dmn
    restart: always
    logging: *default-logging